spring.application.name=logistica_db

# =========================
# ✅ BANCO PRINCIPAL (POSTGRES) - SUA APLICAÇÃO
# =========================
spring.datasource.url=jdbc:postgresql://localhost:5432/logistica_db
spring.datasource.username=${APP_DB_USER:postgres}
spring.datasource.password=${APP_DB_PASS:!info159456@ti}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.defer-datasource-initialization=true

logging.level.org.springframework.security=DEBUG

# =========================
# ✅ BANCO RM (SQL SERVER) - SOMENTE CONSULTA (SEM JPA)
# =========================

rm.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
rm.datasource.url=jdbc:sqlserver://SERVERRM:1433;databaseName=CORPORERM;encrypt=true;trustServerCertificate=true;applicationIntent=ReadOnly
rm.datasource.username=rm
rm.datasource.password=rm


rm.datasource.hikari.maximum-pool-size=5
rm.datasource.hikari.minimum-idle=1
rm.datasource.hikari.connection-timeout=20000
rm.datasource.hikari.read-only=true

# =========================
# ✅ GOOGLE MAPS
# =========================
google.maps.api.key=${GOOGLE_MAPS_API_KEY:}

server.address=0.0.0.0
